name:                HS2048
version:             0.1.0.0
github:              "https://github.com/GordonGgx/HS2048"
license:             BSD3
author:              "ggx"
maintainer:          "abcgg8@qq.com"
copyright:           "2020 ggx"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GordonGgx/HS2048#readme>

dependencies:
- gi-gtk
- gi-gio
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HS2048:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HS2048

tests:
  HS2048-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HS2048
